### ISSUE TITLE
[Feature Request] Loading indicators

### ISSUE THREAD

**Issue by imjoshholloway** [pascalopitz/beanstalk-dashboard-for-chrome#3]
When updating the settings it's unclear that the save button is actually working. Adding a loading indicator and/or a message to say whether the updates have been applied would be good for usability.

**Comment by pascalopitz** [comment]
Saving happened so fast that you never did actually see the indicator. I show it for a second now. You think that's enough? https://github.com/pascalopitz/beanstalk-dashboard-for-chrome/commit/dd3fcfa933451e37ca0f330e4f10ef5f17e6d764

I guess global messages will be better, but I'll have to work on that another day.

**Comment by imjoshholloway** [comment]
Yeah I've used checked and it feels a little more like something is actually happening.

Great work btw. I've been searching for a Beanstalk UI that isn't a full on PHP web app for what feels like an age.

**Comment by pascalopitz** [comment]
Just what I needed to hear :+1: 

Messages coming up, looking into React animate now.

**Comment by pascalopitz** [comment]
Also: What else would you like to see in terms of features?

**Comment by pascalopitz** [comment]
Ok, I have cleaned it all up a bit and now CSS transition messages and loader in smoothly.That should do for now.
